name: Post to Blogger via Email
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  post_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Send Post Script
        env:
          
